### ISSUE TITLE
question

### ISSUE THREAD

**Issue by asaba96** [t-detlefsen/fruit-ninja-vision#3]
does it work with other colors besides orange? i only have white balls.

**Comment by Matthewjsiv** [comment]
i've found that size matters in this case. for example, it seems that my balls were big enough to work with this algorithm but perhaps yours don't meet the requirements? 

let me know if you think this might be the case, we can compare measurements in person if it helps

**Comment by t-detlefsen** [comment]
As mentioned in the README.md, YOLO can be retrained using any color of balls. The model included has been trained only on orange balls. Size should not matter since the RGB-D image is used to determine the real world position.
